version: "3.8"
services:
  discord-bot:
    build: .
    container_name: discord-bot
    env_file:
      - .env
    restart: always
    ports:
      - "5677:5677"
      - "5678:5678"

    volumes:
      - songs-data:/tmp/songs

  mcpo:
    image: ghcr.io/astral-sh/uv:debian
    container_name: mcpo-discord
    entrypoint: ["bash", "-c"]
    command: >
      uvx \
      mcpo \
      --port 5679 \
      --server-type "streamable_http" \
      -- http://127.0.0.1:5678/mcp
    ports:
      - "5679:5679"
    restart: unless-stopped

volumes:
  songs-data:
