services:
  discord-bot:
    build: .
    container_name: discord-bot
    env_file:
      - .env
    restart: always
    ports:
      - "5677:5677"
      - "5678:5678"
    volumes:
      - songs-data:/tmp/songs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5677/health"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

  mcpo:
    image: ghcr.io/open-webui/mcpo:main
    container_name: mcpo-discord
    depends_on:
      discord-bot:
        condition: service_healthy
    command:
      [
        "--host",
        "0.0.0.0",
        "--port",
        "5679",
        "--server-type",
        "streamable_http",
        "--",
        "http://discord-bot:5678/mcp",
      ]
    ports:
      - "5679:5679"
    restart: unless-stopped
    
  mcpo_sse:
    image: ghcr.io/open-webui/mcpo:main
    container_name: mcpo-discord-sse
    depends_on:
      discord-bot:
        condition: service_healthy
    command:
      [
        "--host",
        "0.0.0.0",
        "--port",
        "5675",
        "--server-type",
        "sse",
        "--",
        "http://discord-bot:5678/mcp",
      ]
    ports:
      - "5675:5675"
    restart: unless-stopped

volumes:
  songs-data:
